<?php
session_start();
if(!isset($_SESSION['username'])){
    header("Location: policy.php");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PRIVACY POLICY</title>
    <link rel="stylesheet" href="pro1.css">
    <link rel="stylesheet" href="css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <section class="ssub-header">
    <nav>
            <a href=""><img src="img/l.png" height="50px" width="60px"></a> 
            <div class="nav-links" id="navLinks">
            <i class="fas fa-times" onclick="hideMenu()"></i>
                <ul>
                    <li><h2><a href="logout.php"><?php echo "" . $_SESSION['username']; ?></a></h2></li>
                    <li><a href="pro1.php">HOME</a></li>
                    <li><a href="book.php">CAR</a></li>
                    <li><a href="proAbout.php">ABOUT</a></li>
                    <li><a href="policy.php">POLICY</a></li>
                    <li><a href="contact.php">CONTACT</a></li>
                </ul>
            </div>
            <i class="fas fa-bars" onclick="showMenu()"></i>
        </nav>
        <h1><br><br><br>PRIVARCY POLICY</h1>
    </section>

    <div>
            <p id="c">THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
                THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, TERMS OF SERVICES, PRIVACY POLICY AND USER AGREEMENT FOR ACCESS OR TERMS OF USAGE OF www.lejao.co.in (HEREINAFTER REFERRED TO AS THE “SITE”).
                YOUR USE OF THIS SITE, OR YOUR PROVISION TO USE OF ANY PERSONAL INFORMATION CONSTITUTES YOUR AGREEMENT TO THESE TERMS AND ANY SUBSEQUENT CHANGES TO THESE TERMS; DO NOT USE THE SITE OR PROVIDE INFORMATION IF YOU DO NOT AGREE WITH ALL OF THE TERMS.</p>
            <br><br>
            <h2 id="f1">Privacy Notice</h2> 
            <p id="c1">Though we make every effort to preserve the user privacy, we may need to disclose personal information when required by law wherein we have a good-faith belief that such action is necessary to comply with an appropriate law enforcement investigation, current judicial proceeding, a court order or legal process served on our Site, or as required by law. We may also need to disclose the personal information to a third party for the purpose of delivery of the services to the users.</p>
            <br><br>
            <h2 id="f">General Description</h2>   
            <p id="c">The Site may collect a user's name, postal address, telephone number, mobile number, e- mail address. Besides the above, Members intending to create an account may be asked to submit personal information including driving license, proof of identity etc. besides information pertaining to the Member’s credit card/debit card or bank account details. The Site may also be required to collect the PAN card details and any such detail which is relevant to carry out the transaction. This information is requested if the user is entering into a transaction and is further used to deliver the services as has been requested by the user. The data so collected from the user shall also be used to manage the Site, and detect any fraud or site abuses.
                Other personal information that we collect includes the following:
                Vehicle Use Data: Vehicles will contain hardware that gathers and transmits information about vehicle use. This is done as a security measure against accident or theft and also to provide you with valuable services and information, such as other drivers' data.
                Location Tracking: To prevent theft, and to allow us to locate you in case of emergency, accident, lock-out, etc., we track the location of your vehicle. Your location information will be confined to Revv service, and we will never impermissibly make your location or movements public. As part of our service, the location of your vehicle may be released to insurance companies, the police, or similar parties in the course of an investigation and/or accident claim, and to provide assistance in emergencies. Information regarding the location of each vehicle on Revv’s site is also transmitted to Revv and can be tracked by your Revv-enabled smartphone.
                Driver and Vehicle Information: As a customer of Revv’s Site, you authorize us to access your driver’s record, vehicle history report from all applicable entities and authorities. This authorization continues for as long as you are a Revv customer. Moreover, you authorize all DMVs, RMVs, auto mechanics and all other entities and interested parties to release information to us regarding your driving record and vehicle history.
                You have the right to request that Revv discontinue use of your personal information. To withdraw your consent to our collection and processing of your information at any time, you may do so by closing your account.
                Collection and Use of Non-Personal Information:
                We also collect non-personal information – data in a form that does not permit direct association with any specific individual, including IP addresses, usage details and identifying technologies. We may use, transfer, collect and disclose non-personal information for any purpose. If we do combine non-personal information with personal information, the combined information will be treated as personal information for as long as it remains combined.
                Aggregate Information: We may share non-personally identifiable information (such as referring/exit pages, anonymous usage data, and URLs, platform types, number of clicks, etc.) with interested third parties to help them understand the usage patterns for certain Revv services.
                Third-party ad servers or ad networks may serve advertisements on the Revv Site. These third-party ad servers or ad networks may automatically receive your IP address when they serve ads to your Internet browser. They may also use other technologies (such as cookies, JavaScript, or web beacons) to measure the effectiveness of their advertisements and to personalize the advertising content. We do not provide any personally identifiable information to these third-parties without your consent. However, please note that if an advertiser asks Revv to show an advertisement to a certain audience and you respond to that advertisement, the advertiser or ad-server may conclude that you fit the description of the audience they are trying to reach. The Revv Privacy Policy does not apply to, and we cannot control the activities of, third-party advertisers.
                Normal Browsing <br><br>As with many websites, we collect certain information. When you browse, read, or download information from the Site, data is collected by the Site, including but not limited to your IP address, URL request, browser type, and date and time of your request. We collect the IP addresses of visitors, time of access, browser type, and web pages visited. We do not collect any other information without your knowledge and permission.</p>
                <br><br>
            <h2 id="f2">Information You Provide</h2>    
            <p id="c1">The Site requests personally identifiable information when you seek a query from the Contact Us Tab on the Site and is subject to the Terms of Use. Such information may be used or requested to perform research, improve usability of the site, administer mailing lists or online communities, or other activities related to the services provided by the Site. This information may include, but is not limited to, person’s names, email addresses, location. The above mentioned data is collected by the Site only with the intention to conduct the business and for the facilitation of the correct and timely delivery of the products and improvement of the services. The collected data is preserved with the Site safely and is not sold/disclosed to a third party, whatsoever, beyond the terms of the privacy policy.</p> 
            <br><br>
            <h2 id="f">Disclosure of Information</h2>
            <p id="c">Available log records and all data stored on our servers may be accessed by our system administrators. In the event that we are required by law (including a court order) to disclose the information you submit. We prefer to independently object to overly broad requests for access to information about users of our site, but we cannot assure you that we will be able to do this in all cases. If you do not challenge the disclosure request yourself, we may be legally required to turn over your information.
                The data so collected by the Site may be disclosed to other companies in our group including our agents and subcontractors who help us to deliver the goods to you, collect payments from you, analyse the data and provide us with the marketing or customer service assistance. The data may also be shared for the purpose of the fraud protection, credit risk reduction, for conducting cases. In the event the business or a part of it is sold to any other entity or the business under goes a merger/amalgamation/ demerger, the relevant data may be transferred to such other new entity.
                Besides the above, We reserve the right to transfer any personal information we have about you in the event that we sell or transfer all or a portion of our business or assets.
                We partner with outside companies to provide you with additional services related to Revv, such as ride-sharing or parking benefits. When you purchase, register, or otherwise express interest in a product or service offered by a third party through Revv or sponsored on our site, you consent to our sharing your personal information with those parties. Participation in rewards programs, discount offers, contests, or other programs that involve third parties, authorizes Revv to share your personal information with those parties. A third party’s use of your information is bound by contracts and agreements between Revv and the third party. We only share information reasonably needed to provide additional services, and such shared information may be bound by other privacy agreements. By sharing this information, you agree that Revv is not liable or responsible for the actions or inactions of third parties.</p>
            <br><br>
            <h2 id="f1">Security</h2>    
            <p id="c1">The Site’s primary goal in collecting personal information is to provide you, the member, with a potentially fulfilling experience. The information collected by the Site is protected by the use of appropriate technical and security measures to prevent unauthorized or unlawful access to or accidental loss of or destruction or damage to your information. However, it is brought to your notice that when you use our services or post on the Site, some of the Personal Information you share is visible to other users and can be read, collected, or used by them. You are responsible for such Personal Information you choose to submit in these instances. For example, if you list your name and email address on the site, that information is public. Please take care when using these features. Further, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password.</p>
           
    </div>  
    <section class="footer">
        <h4>About us</h4>
        <p>Lejao-Car, is an Indian self-drive car rental company, headquartered in Maharashtra, India. The company was founded in 2021 by Suraj Sonkar.<br> As of April, the company operates in 12 cities across the country.</p>
        <div class="icons">
            <i class="fab fa-facebook-f"></i>
            <i class="fab fa-twitter"></i>
            <i class="fab fa-instagram"></i>
            <i class="fab fa-linkedin-in"></i>
        </div>
        <p>Always for you to easy your work <i class="far fa-heart"></i></p>
    </section>    

<script>
    var navLiinks = document.getElementById("navLinks");

    function showMenu(){
        navLinks.style.right = "0";
    }
    function hideMenu(){
        navLinks.style.right = "-200px";
    }
</script>
</body>
</html>